import { theme } from '../../styles/theme';

export const styles = {
    page: {
        height: '100vh',
        background: theme.bgPrimary,
        display: 'flex',
        flexDirection: 'column',
        fontFamily: 'system-ui, sans-serif',
        overflow: 'hidden',
    },

    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '16px 24px',
        borderBottom: `1px solid ${theme.borderDefault}`,
        flexShrink: 0,
    },
    logo: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
    },
    logoIcon: {
        fontSize: '20px',
        color: theme.accentBlue,
    },
    logoText: {
        fontSize: '18px',
        fontWeight: '700',
        color: theme.textPrimary,
    },
    logoSubtext: {
        fontSize: '12px',
        color: theme.textMuted,
        marginLeft: '4px',
    },
    headerRight: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
    },
    // Navigation links in the header
navLinks: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flex: 1,
    justifyContent: 'center',
},
navBtn: {
    padding: '8px 14px',
    background: 'transparent',
    border: `1px solid ${theme.borderDefault}`,
    borderRadius: '8px',
    color: theme.textSecondary,
    fontSize: '13px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    whiteSpace: 'nowrap',
},
navBtnActive: {
    background: 'rgba(37, 99, 235, 0.15)',
    borderColor: theme.accentBlue,
    color: theme.textPrimary,
},
    userName: {
        fontSize: '13px',
        color: theme.textSecondary,
    },
    logoutBtn: {
        padding: '8px 14px',
        background: 'transparent',
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '8px',
        color: theme.textSecondary,
        fontSize: '13px',
        cursor: 'pointer',
    },
    // Navigation links in the header (Dashboard / History / Plan / Analytics)
    navLinks: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        flex: 1,
        justifyContent: 'center',
    },
    navBtn: {
        padding: '8px 14px',
        background: 'transparent',
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '8px',
        color: theme.textSecondary,
        fontSize: '13px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        whiteSpace: 'nowrap',
    },
    navBtnActive: {
        background: 'rgba(37, 99, 235, 0.15)',
        borderColor: theme.accentBlue,
        color: theme.textPrimary,
    },
    
    statsBar: {
        display: 'flex',
        gap: '16px',
        padding: '16px 24px',
        borderBottom: `1px solid ${theme.borderDefault}`,
        alignItems: 'center',
        flexWrap: 'wrap',
        flexShrink: 0,
    },
    statCard: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        background: theme.bgSecondary,
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '12px',
        padding: '10px 16px',
    },
    statIcon: {
        fontSize: '18px',
    },
    statValue: {
        fontSize: '18px',
        fontWeight: '700',
    },
    statLabel: {
        fontSize: '11px',
        color: theme.textMuted,
    },
    connectionDot: {
        marginLeft: 'auto',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        fontSize: '12px',
        color: theme.textSecondary,
    },
    dot: {
        width: '8px',
        height: '8px',
        borderRadius: '50%',
    },

    body: {
        flex: 1,
        display: 'grid',
        minHeight: 0,
        overflow: 'hidden',
        transition: 'grid-template-columns 0.3s ease',
    },

    sidebar: {
        borderRight: `1px solid ${theme.borderDefault}`,
        padding: '16px',
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        overflow: 'hidden',
        gap: '12px',
    },

    searchInput: {
        width: '100%',
        padding: '10px 12px',
        background: theme.bgTertiary,
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '10px',
        color: theme.textPrimary,
        fontSize: '13px',
        outline: 'none',
        boxSizing: 'border-box',
        flexShrink: 0,
    },

    vehicleListWrapper: {
        flex: '1 1 0',
        overflowY: 'auto',
        minHeight: 0,
        display: 'flex',
        flexDirection: 'column',
    },

    vehicleList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },

    vehicleItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        padding: '10px',
        background: theme.bgSecondary,
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '10px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        ':hover': {
            background: 'rgba(255,255,255,0.05)',
        },
    },
    checkbox: {
        accentColor: theme.accentBlue,
    },
    vehicleThumbWrap: {
        width: '28px',
        height: '28px',
        borderRadius: '6px',
        overflow: 'hidden',
        background: theme.bgTertiary,
        border: `1px solid ${theme.borderDefault}`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        flexShrink: 0,
    },
    vehicleThumbImg: {
        width: '100%',
        height: '100%',
        objectFit: 'cover',
    },
    vehicleThumbPlaceholder: {
        fontSize: '13px',
    },
    vehiclePlate: {
        fontSize: '13px',
        fontWeight: '600',
        color: theme.textPrimary,
    },
    vehicleDriver: {
        fontSize: '11px',
        color: theme.textMuted,
    },
    statusBadge: {
        fontSize: '10px',
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    emptyText: {
        fontSize: '12px',
        color: theme.textMuted,
        textAlign: 'center',
        padding: '12px',
    },
    planRouteBtn: {
        background: 'transparent',
        border: '1px solid rgba(37, 99, 235, 0.3)',
        borderRadius: '6px',
        padding: '4px 8px',
        color: '#fff',
        fontSize: '14px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        ':hover': {
            background: 'rgba(37, 99, 235, 0.2)',
            borderColor: '#2563EB',
        },
    },

    sidebarFooter: {
        flexShrink: 0,
        borderTop: `1px solid ${theme.borderDefault}`,
        paddingTop: '12px',
        marginTop: '4px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },

    toggleFormsBtn: {
        padding: '10px',
        background: 'transparent',
        border: `1px dashed ${theme.accentBlue}`,
        borderRadius: '10px',
        color: theme.accentBlue,
        fontSize: '12px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        ':hover': {
            background: 'rgba(37, 99, 235, 0.1)',
        },
    },
    formsBlock: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    miniForm: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        background: theme.bgTertiary,
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '10px',
        padding: '12px',
    },
    miniFormTitle: {
        fontSize: '11px',
        fontWeight: '700',
        color: theme.textSecondary,
        textTransform: 'uppercase',
    },
    miniInput: {
        width: '100%',
        padding: '8px 10px',
        background: theme.bgPrimary,
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '8px',
        color: theme.textPrimary,
        fontSize: '12px',
        outline: 'none',
        boxSizing: 'border-box',
    },
    miniBtn: {
        padding: '9px',
        background: theme.accentBlue,
        color: '#fff',
        border: 'none',
        borderRadius: '8px',
        fontSize: '12px',
        fontWeight: '600',
        cursor: 'pointer',
    },

    mapContainer: {
        position: 'relative',
        height: '100%',
        width: '100%',
        overflow: 'hidden',
        background: '#0a0e14',
    },
    placeholder: {
        width: '100%',
        height: '100%',
        background: '#11151c',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#8a93a3',
        fontSize: '0.9rem',
    },

    alertsPanel: {
        borderLeft: `1px solid ${theme.borderDefault}`,
        padding: '16px',
        overflowY: 'auto',
        height: '100%',
    },
    panelTitle: {
        fontSize: '14px',
        fontWeight: '700',
        color: theme.textPrimary,
        margin: '0 0 12px',
    },
    alertForm: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    alertLabel: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        fontSize: '11px',
        color: theme.textSecondary,
    },
    charCount: {
        fontSize: '11px',
        color: theme.textMuted,
    },
    sendAlertBtn: {
        padding: '12px',
        background: theme.accentRed,
        color: '#fff',
        border: 'none',
        borderRadius: '10px',
        fontSize: '13px',
        fontWeight: '700',
        cursor: 'pointer',
    },
    alertHistory: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    alertHistoryItem: {
        background: theme.bgSecondary,
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '10px',
        padding: '10px',
    },
    alertHistoryMsg: {
        fontSize: '12px',
        color: theme.textPrimary,
        marginBottom: '4px',
    },
    alertHistoryMeta: {
        fontSize: '10px',
        color: theme.textMuted,
    },

    layersControl: {
        position: 'absolute',
        top: '12px',
        right: '12px',
        zIndex: 1000,
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        pointerEvents: 'none',
    },
    layerButton: {
        pointerEvents: 'auto',
        padding: '6px 12px',
        borderRadius: '8px',
        border: '1px solid',
        color: '#fff',
        fontSize: '11px',
        fontWeight: '600',
        cursor: 'pointer',
        backdropFilter: 'blur(8px)',
        boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
        fontFamily: 'system-ui, sans-serif',
        transition: 'all 0.2s ease',
        textAlign: 'center',
        minWidth: '130px',
        ':disabled': {
            opacity: 0.4,
            cursor: 'not-allowed',
        },
        ':hover:not(:disabled)': {
            transform: 'scale(1.05)',
        },
    },

    slideOutPanel: {
        background: theme.bgSecondary,
        borderRight: `1px solid ${theme.borderDefault}`,
        padding: '16px',
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        width: '100%',
    },
    slideOutHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingBottom: '12px',
        borderBottom: `1px solid ${theme.borderDefault}`,
        flexShrink: 0,
    },
    slideOutHeaderLeft: {
        flex: 1,
    },
    slideOutClose: {
        background: 'transparent',
        border: 'none',
        color: theme.textMuted,
        fontSize: '18px',
        cursor: 'pointer',
        padding: '4px 8px',
        borderRadius: '4px',
        ':hover': {
            background: 'rgba(255,255,255,0.05)',
        },
    },
    slideOutTitle: {
        fontSize: '18px',
        fontWeight: '700',
        color: theme.textPrimary,
    },
    slideOutRoute: {
        fontSize: '13px',
        color: theme.textSecondary,
        marginTop: '4px',
    },
    slideOutMeta: {
        display: 'flex',
        gap: '16px',
        fontSize: '12px',
        color: theme.textMuted,
        marginTop: '8px',
        flexWrap: 'wrap',
    },
    slideOutBody: {
        flex: 1,
        overflowY: 'auto',
        paddingRight: '4px',
    },
    slideOutEmpty: {
        color: theme.textMuted,
        fontSize: '13px',
        textAlign: 'center',
        padding: '40px 0',
    },

    waypointsList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    waypointItem: {
        padding: '10px 12px',
        borderRadius: '8px',
        border: `1px solid ${theme.borderDefault}`,
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        ':hover': {
            background: 'rgba(255,255,255,0.03)',
        },
    },
    waypointHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '8px',
    },
    waypointKm: {
        fontSize: '12px',
        fontWeight: '600',
        color: theme.textPrimary,
    },
    waypointRisk: {
        fontSize: '10px',
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    waypointExpand: {
        fontSize: '10px',
        color: theme.textMuted,
    },
    waypointDetails: {
        marginTop: '8px',
        paddingTop: '8px',
        borderTop: `1px solid ${theme.borderDefault}`,
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    waypointSummary: {
        fontSize: '12px',
        color: theme.textPrimary,
        lineHeight: 1.4,
    },
    waypointRecommendation: {
        fontSize: '11px',
        color: '#10b981',
    },
    waypointRaw: {
        display: 'flex',
        gap: '12px',
        fontSize: '10px',
        color: theme.textMuted,
        flexWrap: 'wrap',
    },
    waypointSpeed: {
        fontSize: '10px',
        color: theme.textSecondary,
    },

    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0,0,0,0.7)',
        backdropFilter: 'blur(4px)',
        zIndex: 9999,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modal: {
        background: theme.bgSecondary,
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '16px',
        padding: '24px',
        width: '100%',
        maxWidth: '480px',
        maxHeight: '90vh',
        overflowY: 'auto',
        boxShadow: '0 20px 60px rgba(0,0,0,0.5)',
    },
    modalHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '20px',
    },
    modalTitle: {
        fontSize: '18px',
        fontWeight: '700',
        color: theme.textPrimary,
        margin: 0,
    },
    modalClose: {
        background: 'transparent',
        border: 'none',
        color: theme.textMuted,
        fontSize: '18px',
        cursor: 'pointer',
        padding: '4px 8px',
        borderRadius: '4px',
        ':hover': {
            background: 'rgba(255,255,255,0.05)',
        },
    },
    modalBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    label: {
        fontSize: '13px',
        fontWeight: '500',
        color: theme.textSecondary,
    },
    input: {
        width: '100%',
        padding: '10px 12px',
        background: theme.bgTertiary,
        border: `1px solid ${theme.borderDefault}`,
        borderRadius: '8px',
        color: theme.textPrimary,
        fontSize: '14px',
        outline: 'none',
        boxSizing: 'border-box',
    },
    modalSubmitBtn: {
        padding: '12px',
        background: theme.accentBlue,
        color: '#fff',
        border: 'none',
        borderRadius: '10px',
        fontSize: '15px',
        fontWeight: '600',
        cursor: 'pointer',
        marginTop: '8px',
        transition: 'opacity 0.2s',
        ':hover': {
            opacity: 0.9,
        },
        ':disabled': {
            opacity: 0.6,
            cursor: 'not-allowed',
        },
    },
};